name: hibapay
version: 1.0.0+1
publish_to: none
description: A new hibapay project.
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  responsive_sizer: ^3.2.0
  pin_code_fields: ^8.0.1
  google_nav_bar: ^5.0.6
  firebase_core: ^2.24.2
  flutter_svg: ^2.0.9
  flutter_credit_card: ^4.0.1
  animated_rating_bar: ^0.0.8
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  intl: ^0.19.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  fl_chart: ^0.66.1
  flutter_launcher_icons: ^0.13.1
  qr_code_scanner: ^1.0.1
  flutter_fortune_wheel: ^1.3.1
  simple_progress_indicators: ^0.2.0
  local_auth: ^2.2.0



dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  image_path: "assets/images/img_logo.png"
  android:
    adaptive_icon_background: "#FFFFFF"
    adaptive_icon_foreground: "assets/images/img_logo.png"
    round_icon: true
  ios:
    image_path: "assets/images/img_logo.png"
    is_rounded: true
    precomposed: true


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons_png/
    - assets/un_used_images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700


